### ISSUE TITLE
Update wiki page with db script info

### ISSUE THREAD

**Issue by aedwardg** [CodecademyCommunity/codecademy-discord-bot#118]
## Purpose
Update the database wiki page to include info about the new DB scripts

### Is your feature request related to a problem?
The database scripts are only documented in the PR, but should be in the wiki so we can find them.

## Proposed Solution
You can pretty much copy my descriptions from #101 and paste them in the [utilities section](https://github.com/CodecademyCommunity/codecademy-discord-bot/wiki/Database-Setup#utilities) of the wiki page

No PR needed for this, you can either update directly on GH or you can clone the wiki repo, commit directly and push.
Mark this issue as completed when done.

## Acceptance Criteria
- [ ] Accurate descriptions and proper grammar

## Additional context
If you feel like updating any other wiki pages, go for it.

**Comment by fedGL** [comment]
since you wrote the script, it might be easiest for @aedwardg to check this one off?

**Comment by aedwardg** [comment]
Done:

https://github.com/CodecademyCommunity/codecademy-discord-bot/wiki/Database-Utilities
