### ISSUE TITLE
Bot crashes in DM

### ISSUE THREAD

**Issue by Shaylin-TRK** [CodecademyCommunity/codecademy-discord-bot#119]
## Describe the bug
In the event a user DMs the bot with a command that has some form of the `isHighRoller()` function. This is due to the fact that since the user is not considered part of a server at the time `msg.members.role` is equal to `null`.

## To Reproduce
1. DM the bot with cc!kick
2. The bot will crash due to `null` variables.

## Additional context
The bug is fixable by having the condition `if (!(msg.guild === null)) checked before the bot attempts to run commands.

**Comment by aedwardg** [comment]
Rather than having nested `if` blocks, it's probably best to just change the message listener in `app.js` to something like this:
```javascript
client.on('message', (msg) => {
  if (message.channel.type === "dm") {
    return;
  }

  if (msg.content.substring(0, 3) === 'cc!' && !(msg.member === client)) {
    commandParser(msg);
  }
});
```

We could also put a response in before the `return` if we want.

**Comment by aedwardg** [comment]
Another example of how we might address this:
https://discordjs.guide/command-handling/adding-features.html#guild-only-commands

It's fairly similar to what's discussed above.
