### ISSUE TITLE
Refactor timestamp conversion code

### ISSUE THREAD

**Issue by aedwardg** [CodecademyCommunity/codecademy-discord-bot#126]
## Purpose
Refactor time parsing/formatting code to adhere to DRY principle

### Is your feature request related to a problem? Please describe.
There is a large chunk of code that is pretty much identical in [`notes.js`](https://github.com/CodecademyCommunity/codecademy-discord-bot/blob/756e3320f2479aef0d926980831303a60ce2bba8/commands/moderation/notes.js#L89-L112) and [`infractions.js`](https://github.com/CodecademyCommunity/codecademy-discord-bot/blob/756e3320f2479aef0d926980831303a60ce2bba8/commands/utility/infractions.js#L92-L115) that deals with converting timestamps to show "how long ago" something happened. There should be one function that handles this that can be imported and used in any command instead of having it re-defined wherever we need it.

## Proposed Solution
Take this code and put it in a new module and function.  The function will need to take a timestamp as a parameter. Refactor these two commands to use the newly-modularized code.

## Acceptance Criteria
Please list the requirements the implementation of this feature should meet.
- [ ] A new function should be imported to take care of calculating how long ago something happened.
- [ ] `infractions` and `notes` should be refactored to use this function.
- [ ] Code has been linted and formatted with the pre-commit hook.  If the hook isn't working for you, run the CLI commands for Prettier and ESLint discussed in the wiki [here](https://github.com/CodecademyCommunity/codecademy-discord-bot/wiki/Advanced-Setup#prettier-command-line-usage) and [here](https://github.com/CodecademyCommunity/codecademy-discord-bot/wiki/Advanced-Setup#eslint-command-line-usage).

**Comment by mikejoh12** [comment]
What about using the date-fns formatDistanceToNow function for this?
https://date-fns.org/v2.28.0/docs/formatDistanceToNow
If we want to use that we could consider refactoring the functionality using the dateformat library to also use date-fns in order to only have one date/time related library.
