### ISSUE TITLE
Error Handling Needed for Disabled DMs

### ISSUE THREAD

**Issue by aedwardg** [CodecademyCommunity/codecademy-discord-bot#136]
## Describe the bug
For any of the commands that DM the user (ban, tempban, kick, mute, tempmute, unmute, warn), the bot raises a `DiscordAPIError` (and thus an `UnhandledPromiseRejectionWarning`) if the user has DMs disabled in the server.

Unhandled promise rejections are deprecated, so in the future this will crash the bot if the error is not properly handled.

Note: all moderation actions still occur, since the DM is the last step.

## Expected behavior
If a member has DMs disabled, the error should be properly handled and alternative action should take place to notify the user.

A short-term solution would be to use try-catch blocks to handle this, and maybe ping the user in a channel (if the user hasn't been banned or kicked).

## To Reproduce
1. With your alt account, block DMs from the server or block the bot
2. With your admin account, use one of the moderation commands that DMs the user (listed above)
3. See error in your console

### Screenshots
Bug occurs if users have disabled DMs from server members using this setting:

![image](https://user-images.githubusercontent.com/44326005/113095724-d5a7a880-91a8-11eb-8ad7-3a48b3e5c7a3.png)

Or, if they have blocked the bot specifically by right-clicking on the bot and choosing Block:

![image](https://user-images.githubusercontent.com/44326005/113102751-4b187680-91b3-11eb-9143-864c2f75edac.png)

**Comment by Victoria-DR** [comment]
Text commands have been phased out.
