### ISSUE TITLE
cc!warn command warning the wrong user

### ISSUE THREAD

**Issue by Vic-ST** [CodecademyCommunity/codecademy-discord-bot#149]
## Describe the bug
When you warn someone and include an @ to another user in the description but use the User ID to warn the specific user, you warn the user you mentioned in the description

## Expected behavior
It should only use the first user specified, whether by @ or User ID

## To Reproduce
Use the `cc!warn` command but mention a user in the reason for the warn
Example:
```
cc!warn 608641641284370462 Spamming the Mod DMs, please use the @ModMail Bot
```

**Comment by aedwardg** [comment]
I think this can be accomplished with regex similar to how it is explained here:
https://discordjs.guide/miscellaneous/parsing-mention-arguments.html#using-regular-expressions

We may have to alter it a bit if we're already using regex to parse the arguments.

**Comment by mikejoh12** [comment]
Converting to slash commands should fix this issue as the target user can be specified as a selection of the command.

**Comment by Victoria-DR** [comment]
Text commands have been phased out.
