### ISSUE TITLE
Update `cc!ban` to allow for deleting x number of days' messages

### ISSUE THREAD

**Issue by aedwardg** [CodecademyCommunity/codecademy-discord-bot#160]
## Purpose
When we ban someone we can specify the number of days' worth of that user's messages to delete

### Is your feature request related to a problem? Please describe.
Right now, if we ban someone we have to manually delete their messages.

## Proposed Solution
Allow for user to specify the `days` field in the ban options.
The command could be called as `cc!ban @username 7 Example reason`
It may be worth it to change the default to 1 day's worth also.  That way a simple call to `cc!ban` will at least delete the offending messages even if we forget to put the number of days.

See https://discord.js.org/#/docs/main/stable/class/GuildMember?scrollTo=ban

## Acceptance Criteria
Please list the requirements the implementation of this feature should meet.
- [ ] Should allow us to specify the number of days when calling the command.
- [ ] Everything else should still function as normal

**Comment by Victoria-DR** [comment]
I feel that it might be better to have this as a separate command (maybe `cc!purge`?) since we could have uses for this outside of a ban situation. We could just get `cc!ban` to automatically call it for a day, or have another parameter for it.

**Comment by Victoria-DR** [comment]
Text commands have been phased out.
