### ISSUE TITLE
Update `cc!ban` to work on members who have already left the guild

### ISSUE THREAD

**Issue by aedwardg** [CodecademyCommunity/codecademy-discord-bot#163]
## Purpose
To ban members who leave before we can ban them

### Is your feature request related to a problem? Please describe.
Sometimes people get upset about warnings or moderation and leave before we can ban them. We should still be able to ban them from the server, even though they are no longer members.  (Dyno can do this, so it should be possible).

## Proposed Solution
I still need to look into this one, so feel free to comment if you've figured out a solution.

## Acceptance Criteria
Please list the requirements the implementation of this feature should meet.
- [ ] cc!ban command should still work even after user is no longer a member of the server

**Comment by aedwardg** [comment]
After a quick search, it looks like we can do this by using `GuildMemberManager.ban(id)` since that method takes a `UserResolvable`, which can be independent of the guild entirely.

The `GuildMemberManager` is accessed through `guild.members`.

Documentation here:
https://discord.js.org/#/docs/main/stable/class/GuildMemberManager?scrollTo=ban

**Comment by Victoria-DR** [comment]
Text commands have been phased out.
