### ISSUE TITLE
Update the infractions/notes commands to work with people who have left or have been banned

### ISSUE THREAD

**Issue by aedwardg** [CodecademyCommunity/codecademy-discord-bot#164]
## Purpose
This will allow us to look at previous infractions/notes of people who are no longer in the server without having to go manually digging in the database or the audit logs.

### Is your feature request related to a problem? Please describe.
Right now, `cc!infractions` and `cc!notes` only work for current guild members.

## Proposed Solution
We need to be verifying that it is a correct user id in some way that doesn't rely on the person being a current guild member.
Let's look into this and update this issue once we've figured out how.

## Acceptance Criteria
Please list the requirements the implementation of this feature should meet.
- [ ] cc!infractions and cc!notes should work even after a member has left the guild.

**Comment by mikejoh12** [comment]
When converting to slash commands the interaction can ask for a target user. This gives access to a discord User object that we can access for storing or retrieving a note even if the user has left the guild or been banned.

**Comment by Victoria-DR** [comment]
Text commands have been phased out.
