### ISSUE TITLE
Find the Targer!

### ISSUE THREAD

**Issue by aedwardg** [CodecademyCommunity/codecademy-discord-bot#174]
## Describe the bug
We have a few typos (nine, to be exact 😬) in the codebase, where messages say "targer" instead of "target".
Find them all and fix them.

## Expected behavior
The bot should tell us about the "target user", not the "targer user".

### Screenshots
![image](https://user-images.githubusercontent.com/44326005/122990986-5f56b480-d359-11eb-9617-4feab0c8a7e9.png)

## Additional context
If you find any other typos in the bot messages and want to fix them, those changes will be accepted for this issue as well.

_NOTE: This issue does not require local setup of the bot, just a good eye and a sense of humor_ 😄

**Comment by callafeucht** [comment]
Wow, I'm famous! 🤩
