### ISSUE TITLE
Refactor `cc!help` file (make dynamic & add aliases)

### ISSUE THREAD

**Issue by aedwardg** [CodecademyCommunity/codecademy-discord-bot#177]
## Purpose
To clean up the `help.js` file significantly.  Using a switch/case statement was great when we only had a couple of commands, but it's looking crazy now.

## Proposed Solution
We should follow the Discord.js Guide to make our help command dynamic and add aliases to the commands:
https://discordjs.guide/command-handling/adding-features.html#command-aliases
https://discordjs.guide/command-handling/adding-features.html#a-dynamic-help-command

## Acceptance Criteria
Please list the requirements the implementation of this feature should meet.
- [ ] Refactor `help.js` to be clean and dynamic

**Comment by Victoria-DR** [comment]
Text commands have been phased out.
