### ISSUE TITLE
Refactor immunity check

### ISSUE THREAD

**Issue by aedwardg** [CodecademyCommunity/codecademy-discord-bot#203]
## Purpose
We should refactor our immunity check, much like how we refactored the permission handler.  
Right now, we are using various functions all around the codebase such as `isHighRoller` or `notHighRoller`, etc. which is essentially all duplicate code.  Making it modular by importing one function to do this same check everywhere will DRY up the code and be more consistent.

It may be smart to keep this separate from actually applying the immunity handler.  We could update it in batches like we did for the perm handler.

EDIT: Immunity check should also be changed so that FSUs are not immune from moderation commands (-Lyall)

## Proposed Solution
We could essentially clone the permission handling logic, or we could have a function that takes an array of immune roles.
This could be in the permission handler module or in its own, but it may be smart to utilize the existing RoleEnum.

## Acceptance Criteria
Please list the requirements the implementation of this feature should meet.
- [ ] Logic for checking target user immunity is in only one place in the code
- [ ] Code checks if user has some role (or roles) that make the user immune to the bot action
- [ ] FSUs should no longer be immune from moderation commands (-Lyall)
- [ ] Code passes all linting/formatting

## Additional context
Example code that can be refactored and modularized (please remove all those `||` in the conditional too)
https://github.com/CodecademyCommunity/codecademy-discord-bot/blob/26ddcb48a0dab76794e847c9599b06962dd09e38/commands/moderation/addnote.js#L103-L120

**Comment by Victoria-DR** [comment]
Text commands have been phased out.
