### ISSUE TITLE
Create DB_SETUP.md file

### ISSUE THREAD

**Issue by aedwardg** [CodecademyCommunity/codecademy-discord-bot#22]
**Purpose**

The database setup section of `CONTRIBUTING.md` is likely to end up pretty lengthy.  Rather than have it all in `CONTRIBUTING`, I think we should split it out into its own document.  That way we can include some OS-specific troubleshooting tips as we see fit.

**Criteria**

- [ ] Include instructions on getting MySQL setup locally
- [ ] Add a sentence and link in `CONTRIBUTING.md` in the "Set Up Database" section that sends reader to this document.

**Comment by fedGL** [comment]
We could also add a link in CONTRIBUTING.md to a wiki page

**Comment by fedGL** [comment]
Added a new wiki page https://github.com/CodecademyCommunity/codecademy-discord-bot/wiki/Database-stuff
Compiled all the steps I took to set up my db locally on macOS

**Comment by aedwardg** [comment]
Thanks @fedGL that's a really nice comprehensive guide for setting up on macOS!

**Comment by fedGL** [comment]
I just created a new issue #62 to update the CONTRIBUTING.md file and provide more info. I think we can close this now?

**Comment by aedwardg** [comment]
I'm writing up the instructions for Linux and Windows right now.  Will close this issue once that's done!
