### ISSUE TITLE
`cc!ban` does not ban the user if they have DMs disabled 

### ISSUE THREAD

**Issue by lyallstewart** [CodecademyCommunity/codecademy-discord-bot#228]
## Describe the bug
Attemping to ban a user who has DMs disabled from server members will not sucessfully ban the user, instead a DiscordAPIError will be thrown and the user remains in the server (the only way to ban them is via Discord directly or through another bot)

## Expected behavior
The user should be banned regardless of their privacy settings. Although I would suggest that a message be sent in chat letting the moderator know that while the ban was successful, the user would not have recieved the appeal form or reason.

## To Reproduce
1. Disable DMs from server members on an alt account
2. Attempt to ban the alt account via `cc!ban`
3. Error is thrown and user is not banned.

### Screenshots
![image](https://user-images.githubusercontent.com/78568904/149026656-5e563f63-45ef-4c17-9db9-071615440530.png)

## Additional context
Fairly low-priority bug seeing as we can always just ban via Discord but it's also decently important to have users receive the appeal form.

**Comment by Victoria-DR** [comment]
Text commands have been phased out.
