### ISSUE TITLE
Make project wiki or Google doc

### ISSUE THREAD

**Issue by aedwardg** [CodecademyCommunity/codecademy-discord-bot#23]
**Purpose**

We may want to consider having a project wiki or Google doc to reference any important discussion points, etc. that might get lost on Discord.  See [this discussion](https://discord.com/channels/605859344243884081/810011899550892032/810323128969461762) for reference.

**Additional Information**

If we decide to go with a wiki, this issue will need to wait until the GitHub organization is in place and this repo is transferred over.

**Criteria**

- [ ] Come up with a way to document non-trivial group discussions for those who can't keep up with Discord on a daily basis.
- [ ] Make it both creative and organized

**Comment by fedGL** [comment]
Are we in an org now?

**Comment by Vic-ST** [comment]
Yup, so we should be good now

**Comment by fedGL** [comment]
Alright I got big boss to enable wiki so I'll get working on this

**Comment by fedGL** [comment]
I'm thinking on moving some of the more tutorial-is parts of our CONTRIBUTING.md file to the wiki. That will slim down the file. Everything under "Typical Git workflow" will go to the wiki. We keep Initial Setup and reporting issues

**Comment by aedwardg** [comment]
That's fine, but I think they should still be linked to from CONTRIBUTING.md.  

So in CONTRIBUTING, something like 

### Typical Git Workflow
We use a typical Git branching workflow.  See more at our wiki (link to wiki)

---
And then maybe in the wiki we can also throw in this link for further reading
https://git-scm.com/book/en/v2/Git-Branching-Branching-Workflows
