### ISSUE TITLE
Failure to fetch users by ID

### ISSUE THREAD

**Issue by Shaylin-8bit** [CodecademyCommunity/codecademy-discord-bot#231]
## Describe the bug
When using commands like cc!notes cc!infraction cc!verbal or cc!addnote, the bot often fails to get the user based on an ID. This result in the bot saying you forgot to mention the target user. This is true of any file that uses `msg.guild.members.cache.get(args[0])` to get a user I believe because of the way the cache works. To save space the cache only includes users that have triggered one of the bots intents since it was last booted.

## Expected behavior
Bot should be able to get the user based on the id and perform whatever action was taken.

## To Reproduce
This won't always work, but best way I've found to reliably reproduce.
1. Boot up an alt account one the test server bot DO NOT do anything else. (this should keep it from being cached)
2. Boot up your bot, or restart it if it was already running.
3. Call one of the effected commands, like cc!verbal, with your alts ID.
4. The command should fail because it hasn't cached your alts member information.

## Additional context
A work around is to mention the user when calling the command instead of using an ID.

This problem can be fixed by using `msg.guild.members.fetch()` to get all server members, and then using `.get()` with the user ID. This could use some experimenting though. I don't know yet if the function caches all user permanently, and if it does this could clog up RAM a bit with so many member objects. It also would take longer than checking the cache so I fix would probably be best to check the cache before trying `fetch()`. 
Another good point is that this offers an opportunity to be more DRY since this line of code is used in so many files. 

Given there is an easy workaround, and in light of the ongoing port to V13, it would probably be best to wait on doing this for the time being.

**Comment by Victoria-DR** [comment]
Text commands have been phased out.
