### ISSUE TITLE
Port notes commands to v13

### ISSUE THREAD

**Issue by lyallstewart** [CodecademyCommunity/codecademy-discord-bot#232]
## Purpose
Port `cc!notes`, `cc!addnote`, `cc!removenote` to Discord.JS v13

### Is your feature request related to a problem? Please describe.
Currently all our commands (bar a handful like `cc!ping`) require porting over to Discord.JS v13 and the notes commands seemed like a good (albeit artibirtary) place to start. 

Most of the issues around v12 -> v13 are caused by embeds which looks to be a fairly minor change.

## Acceptance Criteria
Please list the requirements the implementation of this feature should meet.
- [ ] Aforementioned commands should work on Discord.JS v13.

**Comment by aedwardg** [comment]
Closed in #264
