### ISSUE TITLE
Port cc!records to v13

### ISSUE THREAD

**Issue by mikejoh12** [CodecademyCommunity/codecademy-discord-bot#253]

**Comment by lyallstewart** [comment]
Given the command just works by calling cc!notes and cc!records, I don't think there's anything in that command itself that needs porting. That said, we should probably refactor this command (see quote from aedwardg below) but that's probably something that can wait until the v13 port is completed imo. More than happy to hear any other thoughts though!

From aedwardg:
As for the alternative way to fetch the infractions/notes, I think if multiple commands are going to use the same functionality then that functionality should live in its own module, which is designed to be reused and can be imported into the commands as necessary. This is a higher-level code structure preference, and I think it's fine to do it in a follow-up refactor PR. Your current solution works, and you did a great job keeping the code DRY, so let's just transition to the new name and then we can spec out a new issue for the modularization of the record fetching.

**Comment by aedwardg** [comment]
If `cc!records` works once the notes and infractions commands are done, I vote we save the refactoring for when we're changing the commands to slash commands.

**Comment by mikejoh12** [comment]
cc!records now works as the underlying commands have been ported.
