### ISSUE TITLE
cc!unban sends conflicting messages when entering user id of a user who is not banned

### ISSUE THREAD

**Issue by mikejoh12** [CodecademyCommunity/codecademy-discord-bot#279]
## Describe the bug
If cc!unban is entered with a user id who is not banned there will be 2 different messages. The bot replies with message: This user is not banned. But in the audit log it will say that user <id> was unbanned. The console will also say 1 record inserted, which indicates that a db entry is made for the unban command with an invalid user id. This was tested on both PR 278 Upgrade to v13 and the dev branch. It occurs on both.

## Expected behavior
cc!unban with an invalid user id should not store a record of unbanning a user in the audit logs. A db entry should also not be made for cc!unban with an invalid user id.

## To Reproduce
1. Enter cc!unban with a valid user id of a user who is not banned
2. Check audit logs
3. Check response from bot
4. Notice the difference in responses

**Comment by Victoria-DR** [comment]
Text commands have been phased out.
