### ISSUE TITLE
Replacing moderation commands warn and infractions

### ISSUE THREAD

**Issue by Vic-ST** [CodecademyCommunity/codecademy-discord-bot#41]
I'd like the commands warn and infractions to be replaced with our own custom commands

#### Command Format
```
cc!warn @ user reason
cc!infractions @ user
cc!addnote @user usernote
cc!notes @user
```
#### Command Usage
The warn commands sends the user a DM saying the reason they've been warned and that they have been. No further action is taken except what is specified in #7 
Pulls all the infractions of a certain user from the database and prints them to the channel in which the command was made.
The addnote command adds a note (a string of text) to a specific user. It should not contact the user who the note was added to in anyway. This should not count as an infraction and should only be logged to the mod_logs table.
The notes command will just display all the notes that have been added to a user.

#### Limited Usage
All of these commands are limited to Super Users, Mods, and Admins

Check issue #7 for more information.

**Comment by fedGL** [comment]
I got the warn down, working on infractions.
Wait.... when a user gets warned, are we updating the db with a new infraction?

**Comment by Vic-ST** [comment]
@fedGL Yes, check #7 for data for insert

**Comment by fedGL** [comment]
Two down, two to go. I'll get started working on `cc!addnote @user usernote` next

**Comment by fedGL** [comment]
@Vic-ST where would the note go? I don't think we have a table for that, do we?

**Comment by Vic-ST** [comment]
@fedGL Honestly, I'd say either a new table or just the mod_logs table. We'll have to reformat the table if we go with the second option but it should work fine.
