### ISSUE TITLE
Audit Log Refactoring

### ISSUE THREAD

**Issue by Vic-ST** [CodecademyCommunity/codecademy-discord-bot#48]
Add code for the audit-logs channel to log important events.

This will include the following:
- Channel creation/deletion
- A role is created/deleted (and all basic info about the role)
- Any server edit
- User changed their nickname

Extremely straightforward, most of the events are on the Discord.js Client page: https://discord.js.org/?source=post_page---------------------------#/docs/main/stable/class/Client

**Comment by Victoria-DR** [comment]
Will get on this once #148 is merged.

**Comment by aedwardg** [comment]
Some (or maybe even all?) of these are covered already by Dyno and/or MEE6 premium now.  We should investigate to see which parts (if any) still need to be implemented by our bot.

**Comment by Victoria-DR** [comment]
I'm closing this issue, as all four of the events to be logged are already recorded in some way. Channel creation/deletion, role creation/deletion, and other server edits, are logged to the #audit-logs channel by Dyno and MEE6. They are also recorded in the Audit Log section of the server settings. Nickname changes are not logged to #audit-logs, but are recorded in the Audit Log section of the server settings. All four are easily searchable in the Audit Log section of the server settings, which can be filtered by user or action to find the relevant event (filters listed below).

Channel creation: Create Channel action
Channel deletion: Delete Channel action
Role creation: Create Role action
Role deletion: Delete Role action
Other server edits: filter by relevant action
Nickname changes: Update Member action, optional filter by user
