### ISSUE TITLE
`cc!stats` power up

### ISSUE THREAD

**Issue by fedGL** [CodecademyCommunity/codecademy-discord-bot#56]
Issues: 
* `cc!stats` prints to the channel but doesn't write to the database
* We are getting minimal data collection (only online, offline, total)
* We don't have a table setup in the database to collect stats

Goals:

- [ ] Decide on the table schema for collecting server insights (what to collect)
- [ ] Set up codebase to use that table
- [ ] Decide at what interval to collect data
- [ ] Update command to collect the data
- [ ] Update command to log to the db

**Comment by fedGL** [comment]
With the advent of our newly paid for "statbot", I think this issue is not irrelevant. If nobody has objections, I'll close it tonight

**Comment by aedwardg** [comment]
No objections from me! It's been almost a week and nobody spoke up, so I'll go ahead an close it.
