### ISSUE TITLE
Update CONTRIBUTING.md

### ISSUE THREAD

**Issue by fedGL** [CodecademyCommunity/codecademy-discord-bot#62]
A few things have changed and we need the CONTRIBUTING.md document updated:

- Add a section "Local Database Setup" that links to the corresponding wiki page
- Add a link to this Ubuntu tutorial for those that aren't on macOS: https://www.digitalocean.com/community/tutorials/how-to-install-mysql-on-ubuntu-20-04

This is a "good first issue", so if you are new to the repo, please don't forget to check the wiki on Git Workflow: https://github.com/CodecademyCommunity/codecademy-discord-bot/wiki/Git-Workflow

**Comment by Victoria-DR** [comment]
Closed by #69.
