### ISSUE TITLE
Add a mild word filter

### ISSUE THREAD

**Issue by Shaylin-TRK** [CodecademyCommunity/codecademy-discord-bot#79]
Add a `wordFilter` default function for the bot to run on messages if they are not commands, then (should it be necessary) delete the message and warn the user. 

* A list of words deemed non-acceptable by staff will need to be made for this.
* Currently an extra `else if` would nee to be added in app.js to call the function since it wouldn't start with cc!:
```
client.on('message', msg => {
  if (msg.content.substring(0, 3) === 'cc!' && !(msg.member === client)) {
    commandParser(msg);
  } else if (!(msg.member === client) {
    // call to function
  }
});
```

On hold until the warning/infractions systems are ready.

**Comment by fedGL** [comment]
I took a quick look at the Server Insights dashboard. It seems we can expect anywhere between 300-500 messages a day in the server. @Vic-ST is there any way of estimating what these number of calls plus CPU to filter them would need from our hosting?

**Comment by Vic-ST** [comment]
@fedGL Nooot really, without adding something to it. Maybe something we can test when you add the stats command to the main bot?
