### ISSUE TITLE
New table to store new messages-per-channel counter

### ISSUE THREAD

**Issue by fedGL** [CodecademyCommunity/codecademy-discord-bot#82]
## Purpose
The bot is going to start tracking message counts across server channels. We need a new table in the server to keep track of it. 

### Is your feature request related to a problem? Please describe.
No, unless not having enough data is a problem. Then yes. You recreate it by looking at an empty table and realizing there isn't any data in it.

## Proposed Solution
Create a new table called "msg_counter" with the following structure:
```
+----+-----------+-------------+
| id | timestamp | channelName |
```

## Acceptance Criteria
Please list the requirements the implementation of this feature should meet.
- [ ] The table is created with the expected structure and appropriate name

## Additional context
Pretty sure @Vic-ST will get 'er done so... no biggie

**Comment by Victoria-DR** [comment]
We've been using snake_case for all DB-related stuff (table names, row names, etc.), so I think we should stick with that? The other option is to change everything over to use camelCase.

**Comment by Vic-ST** [comment]
Don't feel like changing everything over so we'll be sticking to snake case. @fedGL Mind editing the issue?

**Comment by fedGL** [comment]
Changed it to "msg_counter". Gotta keep in mind that a lot of all codebase is currently using camelCase for variable naming, so the question also is "Is it easier to change the SQL table names, or do we live with 2 naming conventions"

**Comment by fedGL** [comment]
@Vic-ST took care of this already
