### ISSUE TITLE
Clean up README.md

### ISSUE THREAD

**Issue by aedwardg** [CodecademyCommunity/codecademy-discord-bot#86]
## Purpose
`README.md` is looking a little chaotic with the way all of our commands are presented.  We should clean these up so they are less prominent in the document.

## Proposed Solution
We can probably utilize markdown tables and/or [collapsible dropdowns](https://gist.github.com/joyrexus/16041f2426450e73f5df9391f7f7ae5f) to clean this up nicely.

For example:
| Command       | Arguments | Permissions | Description                                                               |
|----------------|------------|-------------|-------------------------------------------------------|
| cc!createroles   | N/A           | Admin       | Pulls all badges from Codecademy Discuss and creates a role for each one. |
| cc!sendcode    | [username] | None        |    Sends a verification code to your Codecademy Discuss email.   |

OR:
<details>
<summary>
<strong>CLICK HERE TO SEE COMMANDS</strong>
</summary>

| Command       | Arguments | Permissions | Description                                                               |
|----------------|------------|-------------|-------------------------------------------------------|
| cc!createroles   | N/A           | Admin       | Pulls all badges from Codecademy Discuss and creates a role for each one. |
| cc!sendcode    | [username] | None        |    Sends a verification code to your Codecademy Discuss email.   |

</details>

## Acceptance Criteria
Please list the requirements the implementation of this feature should meet.
- [ ] Make the list of commands take up less space
- [ ] Make it look prettier than we backend devs can 😄

**Comment by Vincent-Projects** [comment]
Hi, I'd be happy to help you with this. I checked your Readme and I think I can make a collapsible markdown for your code snippet to make the file prettier.

**Comment by khafrewatkins** [comment]
Hello, I would like to add my input as well.  I'm sure we can make some good improvements.

**Comment by Vic-ST** [comment]
@Vincent-Projects If you'd like to work on this, take a shot at it and submit a PR
