### ISSUE TITLE
Ineffective bot message filter

### ISSUE THREAD

**Issue by Shaylin-8bit** [CodecademyCommunity/codecademy-discord-bot#93]
## Describe the bug
When a message is sent the bot is supposed to check to make sure it did not send it before performing any action based on it. However the current condition checks two different object types so the bot never thinks it sent a message.

## Expected behavior
The bot should know when a message was sent by itself and skip performing any action with that message.

## To Reproduce
To reproduce you can add a console.log on line 170 just before `commandParser` is called, so that the client.on('message', ...) looks like this:
```
client.on('message', (msg) => {
  if (msg.content.substring(0, 3) === 'cc!' && !(msg.member === client)) {
    console.log("not a bot");
    commandParser(msg);
  }
});
```

You can then run the bot and call the cc!ping command which has the bot send "pong" in response. In the console you'll see "not a bot" logged twice, once for your message and once for the bot's.

## Additional context
There are two ways I know to fix this, you can change `!msg.member == client))` to `!(msg.member.id === client.user.id)` which prevents the bots from working with its own messages, or you can do `!msg.author.bot` which blocks it from working with any bot's messages. Question is do we want other bots to be able to run commands should we ever need to, or block them completely?

**Comment by mikejoh12** [comment]
This does not seem to be an issue anymore. I tested it in the upgrade-to-v13 branch. Can someone else also confirm this. If we agree that is the case then perhaps we can close this issue?

**Comment by Victoria-DR** [comment]
@mikejoh12 Yep, looks like it's been resolved here: https://github.com/CodecademyCommunity/codecademy-discord-bot/blob/000c301e75f6698fa083178539fdd6a10b5bd0d9/handlers/messageHandlers.js#L14
