### ISSUE TITLE
Our `.gitignore` doesn't include `.DS_Store`

### ISSUE THREAD

**Issue by fedGL** [CodecademyCommunity/codecademy-discord-bot#96]
What the title said. Easy fix. But it needs fixing.

why? These are special invisible files macOS produces. If we don't include them in our `.gitignore`, we run the risk of including them in our repo when contributors from that OS push their code.

**Comment by fedGL** [comment]
and come to think of it, we might want to add `package-lock.json` to it too

**Comment by aedwardg** [comment]
We definitely need to ignore `.DS_STORE` files.

As far as `package-lock.json` files, everything I can find online says they are _supposed_ to be tracked by git and shared with team members.  This is supposed to ensure everyone is using the same versions of dependencies and nobody has any issues specific to using an older version.

Unfortunately, if we aren't all using the same npm version and node version, `package-lock.json` becomes really annoying really fast.  
I found this blog post that might help us out?
https://dnasir.com/2018/02/12/solving-the-package-lock-json-integrity-discrepancy/
